version: 2.1
language: java

orbs:
  gradle: circleci/gradle@2.2.0

workflows:
  checkout-build-test:
    jobs:
      - gradle/test:
          store_artifacts: build/reports/
          test_results_path: build/test-results/
